services:
   project_name:
        container_name: project_name
        restart: always
        build: .
        ports:
            - "3000:3000"
        networks:
            - web
networks:
    web:
        external: true